### ISSUE TITLE
Summoner Minions

### ISSUE THREAD

**Issue by sobedragon** [Jofairden/Tremor#42] opened 2018-01-16 19:34 UTC
### tModLoader version

version: v0.10.11

### Tremor version

version: 1.3.2.7

### Description

Summoned Minions birg, slime, blue wind.

### Expected behavior 
When summoned, minions do not despawn after 60 seconds.  Minions become permanent until death or logout.  Can have up to 4 of any with living armor/summoner class.  If you summoned 4 of any, you can't summon any of the others, if you summoned three of one can only summon one of the other so on and so forth.  

### Steps to Reproduce

1. Find a Birch staff
2. Build living armor set
3. Upgrade to summoner class
4. Build a slime staff
5. Summon four slime, try to summon a Birch.  
6. Roam map until dead. 
7. Summon four birch, try to summon slime.  Reload or die.
8.build a blue staff for blue wind.

9. Summon 3 slime 1 birch. Try to summon blue wind.

### Reproduction frequency

How often are you reliably able to reproduce this issue?
Pretty much every time.  Not sure if some summons are more powerful because occasionally the slime staff can overwrite the blue wind miniomn, but not reliably.

### Mods

List all of the mods you are using when reproducing this issue. 
It's appreciated if you could also test this without mods enabled
Discard this if inapplicable

### Additional Information

Additionally, blue wind is awful when it does spawn.  Hardly attacks things.  Birch and a slime will continuously attack something until dead. Sometimes rapidly.  I've had 2 slime rip through 4 or 5 zombies like they are nothing, but if I have blue winds they basically deal little to no damae to even the first zombie before it's on me.

**Comment by Jofairden** [comment] 2018-01-16 21:30
duplicate of: #41
This is intended, the 60 second spawn time displayed in the tooltip is the actual unintended side effect of how these summons are implemented.

**Closed as completed by Jofairden** 2018-01-16 21:30 UTC

**Comment by Jofairden** [comment] 2018-01-16 21:31
Duplicate of #41
This is intended, the 60 second spawn time displayed in the tooltip is the actual unintended side effect of how these summons are implemented.

**Comment by sobedragon** [comment] 2018-01-16 21:37
Fair enough I saw the sixty second timer was removed as a buff, but is it intended that I can't replace a summon with a different summon?  Is there a command to unsummon a minion?

**Comment by whitepyros** [comment] 2018-01-17 00:32
Right click the buff icon for that particular summon
